apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-ai-gateway
  namespace: llm-serving
  labels:
    app.kubernetes.io/name: envoy-ai-gateway
    app.kubernetes.io/part-of: llm-serving
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: envoy-ai-gateway
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
          service.beta.kubernetes.io/aws-load-balancer-listener-attributes.TCP-80: tcp.idle_timeout.seconds=480
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        allocateLoadBalancerNodePorts: false
        externalTrafficPolicy: Cluster