apiVersion: aigateway.envoyproxy.io/v1alpha1 
kind: QuotaPolicy                             
metadata:
  name: deepseek-r1-14b-quota-policy 
  namespace: llm-serving                      
  labels:
    app.kubernetes.io/name: deepseek-r1-14b-quota-policy   
    app.kubernetes.io/part-of: llm-serving    
spec:
  targetRefs:
    - group: aigateway.envoyproxy.io          
      kind: AIServiceBackend                  
      name: deepseek-r1-14b                   
  perModelQuotas:
  - modelName: /models
    quota:
      defaultBucket:
        limit: 1000
        duration: 1d
      bucketRules:
        - clientSelectors:
            - headers:
                - name: x-client-id
                  type: Exact
                  value: development-client
          quota:
            limit: 1000
            duration: 1d
